Repository glpi-project/android-inventory-agent, pull requests merged in 2018-12, with the labels that each got.

#235 Add languages in Transifex
  .tx/config
Labels: ci

#238 Add compatibility with Android
  README.md
Labels: documentation

#234 Add missing permissions
  app/src/main/java/org/flyve/inventory/agent/core/permission/PermissionModel.java
  app/src/main/java/org/flyve/inventory/agent/ui/ActivityInventoryReport.java
  app/src/main/java/org/flyve/inventory/agent/ui/ActivityMain.java
  app/src/main/java/org/flyve/inventory/agent/ui/PermissionActivity.java
Labels: bug

#232 Copy Text in screen Show Inventory
  app/src/main/res/layout/list_item_inventory_child.xml
Labels: feature

#239 Fix path for code documentation
  ci/scripts/create_documentation.sh
  ci/scripts/generate_documentation.sh
Labels: ci, dependent, documentation

#245 Delete ChangeLogs of candidates
  CHANGELOG.md
Labels: documentation
